[package]
name = "rust-calculator"
version = "1.0.0"
authors = ["oralekin <oralekin@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
